### Created By: ESAB
### Sales_OLTP Data System
### Date: 09-04-2026

# ETL Using Python
## 1 - Extract Stage

In [2]:
!pip install pyodbc

Requirement already satisfied: pyodbc in c:\users\5g\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (5.3.0)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: C:\Users\5g\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [3]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\5g\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (2.3.2)
Requirement already satisfied: numpy>=1.23.2 in c:\users\5g\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\5g\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\5g\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\5g\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\5g\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: C:\Users\5g\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [5]:
import pyodbc 
import pandas as pd

In [6]:
pyodbc.drivers()  # List available ODBC drivers

['SQL Server',
 'ODBC Driver 17 for SQL Server',
 'ODBC Driver 18 for SQL Server',
 'Microsoft Access Driver (*.mdb, *.accdb)',
 'Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)',
 'Microsoft Access Text Driver (*.txt, *.csv)',
 'Microsoft Access dBASE Driver (*.dbf, *.ndx, *.mdx)']

In [ ]:
# Establish connection to the source database
source_conn = pyodbc.connect(
    "DRIVER={ODBC Driver 17 for SQL Server};"
    "SERVER=.\SQLEXPRESS;"
    "DATABASE=Sales_OLTP;"
    "Trusted_Connection=yes;"
    )

In [9]:
# Working On DimCustomer table
customer_df = pd.read_sql("select * from Customer", source_conn)
customer_df

C:\Users\5g\AppData\Local\Temp\ipykernel_8288\3578689840.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  customer_df = pd.read_sql("select * from Customer", source_conn)

,CustomerID,FirstName,LastName,Email,PhoneNumber,GenderID,LastModifiedDate,is_current
0,1,John,Doe,john.doe@email.com,123-456-7890,1,2023-01-01,True
1,2,Jane,Smith,jane.smith@email.com,987-654-3210,2,2023-01-01,True
2,3,Alice,Johnson,alice.johnson@email.com,111-222-3333,3,2023-01-01,True
3,4,Bob,Smith,bob.smith@email.com,444-555-6666,1,2023-01-01,True
4,5,Eva,Davis,eva.davis@email.com,777-888-9999,2,2023-01-01,True
5,6,Michael,Williams,michael.williams@email.com,555-111-2222,1,2023-01-01,True
6,7,Sophia,Brown,sophia.brown@email.com,555-333-4444,2,2023-01-01,True
7,8,Oliver,Jones,oliver.jones@email.com,555-555-6666,1,2023-01-01,True
8,9,Emma,Garcia,emma.garcia@email.com,555-777-8888,2,2023-01-01,True
9,10,Jackson,Martinez,jackson.martinez@email.com,555-999-0000,1,2023-01-01,True

In [22]:
# We need also Gender Name, so we will use left outer join,
# we need CustomerID-->PK, FullName, PhoneNumber, Email, GenderName
customer_df = pd.read_sql("select CustomerID," \
" CONCAT(FirstName ,' ' ,LastName) as FullName,PhoneNumber as Phone," \
" Email, GenderName from Customer c " \
"left outer join Gender g " \
"on c.GenderID = g.GenderID", source_conn)
customer_df

C:\Users\5g\AppData\Local\Temp\ipykernel_8288\2870742698.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  customer_df = pd.read_sql("select CustomerID," \

,CustomerID,FullName,Phone,Email,GenderName
0,1,John Doe,123-456-7890,john.doe@email.com,Male
1,2,Jane Smith,987-654-3210,jane.smith@email.com,Female
2,3,Alice Johnson,111-222-3333,alice.johnson@email.com,Other
3,4,Bob Smith,444-555-6666,bob.smith@email.com,Male
4,5,Eva Davis,777-888-9999,eva.davis@email.com,Female
5,6,Michael Williams,555-111-2222,michael.williams@email.com,Male
6,7,Sophia Brown,555-333-4444,sophia.brown@email.com,Female
7,8,Oliver Jones,555-555-6666,oliver.jones@email.com,Male
8,9,Emma Garcia,555-777-8888,emma.garcia@email.com,Female
9,10,Jackson Martinez,555-999-0000,jackson.martinez@email.com,Male

In [23]:
# Working On DimProduct table ProductID --> PK, ProductName, Price, SubCategoryName, CategoryName
product_df = pd.read_sql("select ProductID, ProductName, Price, SubCategoryName,CategoryName" \
" from prod_view p left outer join Category c " \
"on p.CategoryID = c.CategoryID ",source_conn)
product_df

C:\Users\5g\AppData\Local\Temp\ipykernel_8288\1135722923.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  product_df = pd.read_sql("select ProductID, ProductName, Price, SubCategoryName,CategoryName" \

,ProductID,ProductName,Price,SubCategoryName,CategoryName
0,1,"HL Road Frame - Black, 588",1431.50,Road Frames,Components
1,2,"HL Road Frame - Red, 58",1431.50,Road Frames,Components
2,3,"Sport-100 Helmet, Red",34.99,Helmets,Accessories
3,4,"Sport-100 Helmet, Black",34.99,Helmets,Accessories
4,5,"Mountain Bike Socks, M",9.50,Socks,Clothing
...,...,...,...,...,...
70,71,Water Bottle - 30 oz.,4.99,Bottles and Cages,Accessories
71,72,Patch Kit/8 Patches,2.29,Tires and Tubes,Accessories
72,73,Mountain Tire Tube,4.99,Tires and Tubes,Accessories
73,74,Road Tire Tube,3.99,Tires and Tubes,Accessories
74,75,Touring Tire Tube,4.99,Tires and Tubes,Accessories

In [24]:
# Working On DimSalesMan table SalesManID --> PK, FullName, Phone, Email, City
salesman_df = pd.read_sql("select * from salesman_view", source_conn)
salesman_df

C:\Users\5g\AppData\Local\Temp\ipykernel_8288\1775829054.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  salesman_df = pd.read_sql("select * from salesman_view", source_conn)

,SalesManID,FullName,Email,Phone,City
0,1,Mike Johnson,mike.johnson@email.com,555-123-4567,Cityville
1,2,Emily Taylor,emily.taylor@email.com,555-222-3333,Townsville
2,3,William Johnson,william.johnson@email.com,555-444-5555,Cityville
3,4,Ava Davis,ava.davis@email.com,555-666-7777,Villageton
4,5,Ethan Miller,ethan.miller@email.com,555-888-9999,Cityville
5,6,Sophie Anderson,sophie.anderson@email.com,555-000-1111,Townsville

In [25]:
# Working on FactOrders table
factorders_df = pd.read_sql("select * from order_view", source_conn)
factorders_df

C:\Users\5g\AppData\Local\Temp\ipykernel_8288\3690153974.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  factorders_df = pd.read_sql("select * from order_view", source_conn)

,OrderID,ProductID,CustomerID,SalesManID,Order_Date,Quantity,TotalPrice
0,1,22,3,4,2023-01-01 10:00:00,3,1011.66
1,1,15,3,4,2023-01-01 10:00:00,5,7157.50
2,1,1,3,4,2023-01-01 10:00:00,6,8589.00
3,2,7,8,6,2023-01-01 11:30:00,4,139.96
4,2,13,8,6,2023-01-01 11:30:00,22,31493.00
5,3,33,3,6,2023-01-02 08:45:00,7,2360.54
6,4,9,3,6,2023-01-02 09:15:00,3,149.97
7,4,10,3,6,2023-01-02 09:15:00,5,249.95
8,5,4,5,4,2023-01-02 12:20:00,3,104.97
9,6,45,1,2,2023-02-07 11:30:00,2,7156.54
10,6,12,1,2,2023-02-07 11:30:00,5,249.95
11,6,7,1,2,2023-02-07 11:30:00,4,139.96
12,7,34,2,4,2023-02-07 13:45:00,1,337.22
13,8,4,8,3,2023-02-07 15:00:00,2,69.98
14,9,39,6,1,2023-03-03 13:10:00,3,4048.80
15,10,52,2,6,2023-04-08 11:25:00,6,8747.94
16,11,70,3,2,2023-04-08 12:00:00,5,16999.95
17,11,57,3,2,2023-04-08 12:00:00,8,6263.92
18,11,63,3,2,2023-04-08 12:00:00,2,1565.98
19,11,43,3,2,2023-04-08 12:00:00,1,1349.60

## 2 - Transform

In [26]:
customer_df.head()

   CustomerID       FullName         Phone                    Email GenderName
0           1       John Doe  123-456-7890       john.doe@email.com       Male
1           2     Jane Smith  987-654-3210     jane.smith@email.com     Female
2           3  Alice Johnson  111-222-3333  alice.johnson@email.com      Other
3           4      Bob Smith  444-555-6666      bob.smith@email.com       Male
4           5      Eva Davis  777-888-9999      eva.davis@email.com     Female

In [27]:
customer_df.dtypes

CustomerID     int64
FullName      object
Phone         object
Email         object
GenderName    object
dtype: object

In [28]:
customer_df.isnull().sum()

CustomerID    0
FullName      0
Phone         0
Email         0
GenderName    0
dtype: int64

In [50]:
# remove dash from phone nubmer
customer_df['Phone'] = customer_df['Phone'].replace('-', '')
customer_df.head()

   CustomerID       FullName       Phone                    Email GenderName
0           1       John Doe  1234567890       john.doe@email.com       Male
1           2     Jane Smith  9876543210     jane.smith@email.com     Female
2           3  Alice Johnson  1112223333  alice.johnson@email.com      Other
3           4      Bob Smith  4445556666      bob.smith@email.com       Male
4           5      Eva Davis  7778889999      eva.davis@email.com     Female

In [34]:
product_df.head()

   ProductID                 ProductName    Price SubCategoryName CategoryName
0          1  HL Road Frame - Black, 588  1431.50     Road Frames   Components
1          2     HL Road Frame - Red, 58  1431.50     Road Frames   Components
2          3       Sport-100 Helmet, Red    34.99         Helmets  Accessories
3          4     Sport-100 Helmet, Black    34.99         Helmets  Accessories
4          5      Mountain Bike Socks, M     9.50           Socks     Clothing

In [35]:
product_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ProductID        75 non-null     int64
 1   ProductName      75 non-null     object
 2   Price            75 non-null     float64
 3   SubCategoryName  75 non-null     object
 4   CategoryName     75 non-null     object
dtypes: float64(1), int64(1), object(3)
memory usage: 3.1+ KB

In [36]:
product_df.isnull().sum()

ProductID          0
ProductName        0
Price              0
SubCategoryName    0
CategoryName       0
dtype: int64

In [38]:
salesman_df.head()

,SalesManID,FullName,Email,Phone,City
0,1,Mike Johnson,mike.johnson@email.com,555-123-4567,Cityville
1,2,Emily Taylor,emily.taylor@email.com,555-222-3333,Townsville
2,3,William Johnson,william.johnson@email.com,555-444-5555,Cityville
3,4,Ava Davis,ava.davis@email.com,555-666-7777,Villageton
4,5,Ethan Miller,ethan.miller@email.com,555-888-9999,Cityville

In [39]:
salesman_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SalesManID  6 non-null      int64
 1   FullName    6 non-null      object
 2   Email       6 non-null      object
 3   Phone       6 non-null      object
 4   City        6 non-null      object
dtypes: int64(1), object(4)
memory usage: 372.0+ bytes

In [41]:
salesman_df.isnull().sum()

SalesManID    0
FullName      0
Email         0
Phone         0
City          0
dtype: int64

In [49]:
# remove dash from phone nubmer
salesman_df['Phone'] = salesman_df['Phone'].replace('-', '')
salesman_df.head()

,SalesManID,FullName,Email,Phone,City
0,1,Mike Johnson,mike.johnson@email.com,5551234567,Cityville
1,2,Emily Taylor,emily.taylor@email.com,5552223333,Townsville
2,3,William Johnson,william.johnson@email.com,5554445555,Cityville
3,4,Ava Davis,ava.davis@email.com,5556667777,Villageton
4,5,Ethan Miller,ethan.miller@email.com,5558889999,Cityville

In [43]:
factorders_df.head()

,OrderID,ProductID,CustomerID,SalesManID,Order_Date,Quantity,TotalPrice
0,1,22,3,4,2023-01-01 10:00:00,3,1011.66
1,1,15,3,4,2023-01-01 10:00:00,5,7157.50
2,1,1,3,4,2023-01-01 10:00:00,6,8589.00
3,2,7,8,6,2023-01-01 11:30:00,4,139.96
4,2,13,8,6,2023-01-01 11:30:00,22,31493.00

In [44]:
factorders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   OrderID     20 non-null     int64
 1   ProductID   20 non-null     int64
 2   CustomerID  20 non-null     int64
 3   SalesManID  20 non-null     int64
 4   Order_Date  20 non-null     datetime64[ns]
 5   Quantity    20 non-null     int64
 6   TotalPrice  20 non-null     float64
dtypes: datetime64[ns](1), float64(1), int64(5)
memory usage: 1.2 KB

In [46]:
# order_date is date not int so we need to change it to int to be able to load it in the data warehouse
# also convert it from 2023-01-01 10:00:00 to 20230101
factorders_df['Order_Date'] = factorders_df['Order_Date'].dt.strftime('%Y%m%d').astype(int)
factorders_df.head()

,OrderID,ProductID,CustomerID,SalesManID,Order_Date,Quantity,TotalPrice
0,1,22,3,4,20230101,3,1011.66
1,1,15,3,4,20230101,5,7157.50
2,1,1,3,4,20230101,6,8589.00
3,2,7,8,6,20230101,4,139.96
4,2,13,8,6,20230101,22,31493.00

In [51]:
# convert quantity to flaot64
factorders_df['Quantity'] = factorders_df['Quantity'].astype('float64')

In [52]:
factorders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   OrderID     20 non-null     int64
 1   ProductID   20 non-null     int64
 2   CustomerID  20 non-null     int64
 3   SalesManID  20 non-null     int64
 4   Order_Date  20 non-null     int64
 5   Quantity    20 non-null     float64
 6   TotalPrice  20 non-null     float64
dtypes: float64(2), int64(5)
memory usage: 1.2 KB

## 3 - Load

In [86]:
# Establish connection to the Destination database TO DWH
destination_conn = pyodbc.connect(
    "DRIVER={ODBC Driver 17 for SQL Server};"
    "SERVER=.\SQLEXPRESS;"
    "DATABASE=Sales_DWH;"
    "Trusted_Connection=yes;"
    )

In [79]:
for index, row in customer_df.iterrows():
    cursor = destination_conn.cursor()
    cursor.execute("INSERT INTO DimCustomer (CustomerID, FullName, Phone, Email, GenderName) VALUES (?, ?, ?, ?, ?)",
                   row['CustomerID'], row['FullName'], row['Phone'], row['Email'], row['GenderName'])
    destination_conn.commit()

In [80]:
for index, row in product_df.iterrows():
    cursor = destination_conn.cursor()
    cursor.execute("INSERT INTO DimProduct (ProductID, ProductName, Price, SubCategoryName, CategoryName) VALUES (?, ?, ?, ?, ?)",
                   row['ProductID'], row['ProductName'], row['Price'], row['SubCategoryName'], row['CategoryName'])
    destination_conn.commit()

In [81]:
for index, row in salesman_df.iterrows():
    cursor = destination_conn.cursor()
    cursor.execute("INSERT INTO DimSalesMan (SalesManID, FullName, Phone, Email, City) VALUES (?, ?, ?, ?, ?)",
                   row['SalesManID'], row['FullName'], row['Phone'], row['Email'], row['City'])
    destination_conn.commit()

In [87]:
for index, row in factorders_df.iterrows():
    cursor = destination_conn.cursor()
    cursor.execute("INSERT INTO FactOrders (OrderID, ProductID, CustomerID, SalesManID, Order_Date, Quantity,TotalPrice) VALUES (?, ?, ?, ?, ?, ?, ?)",
                   row['OrderID'], row['ProductID'], row['CustomerID'], row['SalesManID'], row['Order_Date'], row['Quantity'], row['TotalPrice'])
    destination_conn.commit()

In [88]:
cursor.close()
destination_conn.close()